import { AlertTriangle, BrainCircuit, Sparkles } from "lucide-react";

import type { PredictionResponse } from "../lib/types";

interface PredictionResultsProps { result: PredictionResponse | null; loading: boolean; error: string | null; }

export function PredictionResults({ result, loading, error }: PredictionResultsProps) {
  return <aside className="rounded-2xl border border-slate-200 bg-white shadow-sm xl:sticky xl:top-5"><div className="border-b border-slate-100 p-5"><div className="flex items-center gap-3"><span className="grid size-9 place-items-center rounded-xl bg-violet-50 text-violet-700"><BrainCircuit className="size-4" /></span><div><h2 className="font-semibold text-slate-950">Orientation results</h2><p className="text-sm text-slate-500">Possible pathologies, ranked by probability.</p></div></div></div><div className="p-5">{loading && <LoadingState />}{!loading && error && <div className="rounded-2xl border border-red-200 bg-red-50 p-4 text-sm text-red-800"><div className="mb-1 flex items-center gap-2 font-semibold"><AlertTriangle className="size-4" />Unable to analyze this input</div>{error}</div>}{!loading && !error && !result && <EmptyResults />}{!loading && result && <ResultList result={result} />}</div></aside>;
}

function EmptyResults() { return <div className="grid min-h-96 place-items-center text-center"><div><span className="mx-auto mb-4 grid size-12 place-items-center rounded-2xl bg-violet-50 text-violet-700"><Sparkles className="size-5" /></span><h3 className="font-medium text-slate-900">Ready when you are</h3><p className="mx-auto mt-2 max-w-xs text-sm leading-6 text-slate-500">Complete patient information and add observed evidence to view the model’s Top‑5 orientation results.</p></div></div>; }

function LoadingState() { return <div className="space-y-5 py-3">{Array.from({ length: 5 }, (_, index) => <div key={index} className="animate-pulse"><div className="mb-2 h-4 w-3/4 rounded bg-slate-100" /><div className="h-2 rounded-full bg-slate-100" /></div>)}</div>; }

function ResultList({ result }: { result: PredictionResponse }) { return <div className="space-y-5">{result.confidence.low_confidence && <div className="rounded-xl border border-amber-200 bg-amber-50 p-3 text-sm text-amber-900"><div className="flex items-center gap-2 font-semibold"><AlertTriangle className="size-4" />Low confidence</div><p className="mt-1 leading-5">Consider providing more evidence before interpreting these orientation results.</p></div>}<ol className="space-y-4">{result.predictions.map((prediction) => <li key={prediction.pathology}><div className="mb-2 flex items-start justify-between gap-3"><p className="text-sm font-medium leading-5 text-slate-900"><span className="mr-2 text-cyan-700">{String(prediction.rank).padStart(2, "0")}</span>{prediction.pathology}</p><span className="shrink-0 text-sm font-semibold tabular-nums text-slate-700">{(prediction.probability * 100).toFixed(2)}%</span></div><div className="h-2 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-gradient-to-r from-cyan-600 to-blue-600" style={{ width: `${Math.max(prediction.probability * 100, 1)}%` }} /></div></li>)}</ol><p className="border-t border-slate-100 pt-4 text-xs leading-5 text-slate-500">{result.disclaimer}</p></div>; }
